browser = chrome
url = https://naveenautomationlabs.com/opencart/index.php?route=account/login

username = utkarsh.che@gmail.com
password = uttuudut

headless = false
incognito = false

highlight = false

remote = true
#huburl = http://13.126.85.16:4444/wd/hub
huburl = http://localhost:4444/wd/hub